title: My Blog
author: VirusPc
email: your-email@domain.com
description: 懒癌晚期

# social links
email: pc479684801@outlook.com
twitter_username: VirusPc7
github_username:  VirusPc
qq: 479684801

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
